In [ ]:
pip install SimpleITK

In [ ]:
# IMPORTS #

import numpy as np
import matplotlib.pyplot as plt
import SimpleITK

In [ ]:
# MODULE IMPORTS # (because Jupyter NoteBooks can't import other Notebooks classes)

# Should be -----------------------
# import Image
#----------------------------------

def rgb2grey(rgb):
    """
        Creates a luma transformation of an rgb array
        
        :param rgb: a list of arrays
        :type rgb: numpy.ndarray
        :return: the grey array
        :rtype: numpy.ndarray
        
        :Example:
        
        >>> import numpy
        >>> a = numpy.array([1,2,3])
        >>> print(rgb2grey(a))
        [1.8596 1.8596 1.8596]
    """
    luma = rgb[0] * luma_coeff[0] + rgb[1] * luma_coeff[1] + rgb[2] * luma_coeff[2]
    formula = [luma, luma, luma]
    return np.array(formula)

luma_coeff = [0.2126, 0.7152, 0.0722]

class Image:
    
    def __init__(self, fn='', fromArray=np.array([])):
        assert fn or fromArray.ndim>=2, "Image must take a filename or a numpy array as a parameter"
        if fn:
            img = SimpleITK.ReadImage(fn)
            self.__filename = fn
            self.__width = img.GetWidth()
            self.__height = img.GetHeight()
            self.__array = SimpleITK.GetArrayFromImage(img)
            self.__array = self.__array / 65535.0
        else:
            self.__filename = None
            self.__width = fromArray.shape[1]
            self.__height = fromArray.shape[0]
            self.__array = fromArray / 65535.0
    
    def get_filename(self):
        return self.__filename
    
    def get_array(self):
        return self.__array
    
    def get_grey_array(self):
        grey_array = []
        for i in range(len(self.get_array())): # not optimized
            inter = []
            for j in range(len(self.get_array()[i])):
                inter.append(rgb2grey(self.get_array()[i][j]))
            grey_array.append(np.array(inter))

        return np.array(grey_array)
    
    def get_width(self):
        return self.__width
    
    def get_height(self):
        return self.__height
    
    def show(self, mode=''):
        if 'r' in mode:
            dir ='lower'
        else:
            dir = 'upper'
        if 'g' in mode:
            plt.imshow(self.get_grey_array(), origin=dir)
        else:
            plt.imshow(self.get_array(), origin=dir)

In [ ]:
# FUNCTIONS #

def get_med_img(arr):
    """
        Creates a median array from a list of arrays
        
        :param arr: a list of arrays
        :type arr: list or numpy.ndarray
        :return: the median array
        :rtype: numpy.ndarray
        
        :Example:
        
        >>> import numpy
        >>> a = numpy.array([[7,8,9],[16,17,18]])
        >>> b = numpy.array([[13,14,15],[4,5,6]])
        >>> c = numpy.array([[1,2,3],[10,11,12]])
        >>> print(get_med_img([a, b, c]))
        [[ 7.  8.  9.]
         [10. 11. 12.]]
    """
    l3d = np.array(arr)
    return np.median(l3d, axis=0)

In [ ]:
# ACTUAL CLASS #

class Image3dConverter:
    
    def __init__(self, fns, path=''):
        arrays = []
        for i in range(len(fns)):
            img = SimpleITK.ReadImage(path + fns[i])
            arrays.append(SimpleITK.GetArrayFromImage(img))
        self.__image = Image(fromArray=get_med_img(arrays))
    
    def get_2dImage(self):
        return self.__image
    
    def get_width(self):
        return self.get_2dImage().get_width()
    
    def get_height(self):
        return self.get_2dImage().get_height()
    
    def get_array(self):
        return self.get_2dImage().get_array()
    
    def show(self, mode):
        self.get_2dImage().show(mode)

In [ ]:
# TESTING #

files = ['scan1.tif', 'scan2.tif', 'scan3.tif', 'scan4.tif', 'scan5.tif']
img1 = Image3dConverter(files, 'tif1/')
img1.show('r')